[build]
  functions = "netlify/functions"
  command = "npm ci --prefix mobile && npm ci --prefix netlify && cd mobile && npx --yes expo export --platform web --output-dir web-build"
  publish = "mobile/web-build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[template.environment]
  SUPABASE_URL = ""
  SUPABASE_SERVICE_ROLE_KEY = ""
  SUPABASE_BUCKET = "documents"
  MP_ACCESS_TOKEN = ""
  MP_PUBLIC_KEY = ""
  WEBHOOK_URL = ""
  SUCCESS_URL = ""
  FAILURE_URL = ""
  PENDING_URL = ""
  URL = ""
  EXPO_PUBLIC_API_BASE = ""
  EXPO_PUBLIC_API_BASE_URL = ""